### ISSUE TITLE
ProgressBar does not fit its container by default

### ISSUE THREAD

**Issue by tkrugg** [ibm-js/deliteful#127]
To reproduce this

``` html
<body>
     <d-progress-bar ...></d-progress-bar>
</body>
```

You can see a scroll bar appear at the bottom of the window.

it appears to be caused by this property:

``` css
.d-progress-bar {
    margin: 2px;
}
```
