### ISSUE TITLE
ProgressIndicator: Customizing colors doesn't work on IE

### ISSUE THREAD

**Issue by EAlexRojas** [ibm-js/deliteful#566]
Changing the properties related to the text color and lines color as described on documentation:

``` css
.d-progress-indicator-lines {
  stroke: red;
}
.d-progress-indicator text {
  fill: red;
}
```

But on IE, the text and lines are still displayed in black. 

Code used: 

``` html
<d-progress-indicator id="pi" active="true" value="30"></d-progress-indicator>
```
